import type { NextPage } from 'next'
import Head from 'next/head'
import { TodoApp } from 'app/TodoApp'

const Home: NextPage = () => {
  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap"
        rel="stylesheet" />
    </Head>
    <TodoApp />
  </>)
}

export default Home
